contactapp/urls.py
from django.urls import path, include
from . import views

app_name = 'contactapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contact',views.ContactFormView.as_view(),name='contact')
]

contactproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contactapp.urls')),
]

contactapp/models.py
from django.db import models

# Create your models here.

contactapp/forms.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError,send_mail
from django.http import HttpResponse


class ContactForm(forms.Form):
    name=forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'お名前',
        })
    )
    email=forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class':'form-control',
            'placeholder':'メールアドレス',
        })
    )
    subject=forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'件名',
        })
    )
    message=forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class':'form-control',
            'placeholder':'お問い合わせ内容'
        })
    )

    def send_email(self):
        subject=self.cleaned_data['subject']
        message=self.cleaned_data['message']
        name=self.cleaned_data['name']
        email=self.cleaned_data['email']
        from_email='{name} <{email}>'.format(name=name,email=email)
        recipient_list = [settings.EMAIL_HOST_USER]
        try:
            send_mail(subject,message,from_email,recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

contactapp/views.py
from django.shortcuts import render,resolve_url 
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from .forms import ContactForm
from django.contrib import messages


class Index(TemplateView):
    template_name='contactapp/index.html'

class ContactFormView(FormView):
    template_name='contactapp/contact_form.html'
    form_class=ContactForm
    # success_url=reverse_lazy('contactapp:index')

    def form_valid(self,form):
        form.send_email()
        return super().form_valid(form)

    def get_success_url(self):
        messages.info(self.request,'お問い合わせは正常に送信されました。')
        return resolve_url('contactapp:index')

contactapp/templates/contactapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>コメント欄</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <!--Navbar-->
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color fixed-top" role="navigation">

  <!-- Navbar brand -->


  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/" target="_blank">ホーム</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin" target="_blank">管理画面へ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contactapp:contact' %}" target="_blank">お問い合わせ</a>
      </li>
      
    </ul>
    <!-- Links -->

  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->
<!--/.Navbar-->
    <main class="container" style="padding-top:60px;">
    {% if messages %}
    <br>
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{message}}
        </div>  
      {% endfor %} 
    {% endif %}

    {% block content %}        
    {% endblock %}
    </main>
  <!-- /Start your project here-->

  <!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic" href="https://github.com/Ntsoccer">
            <i class="fab fa-github fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic" href="https://twitter.com/N_T_soccer0512">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> Takuya Nishimura</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

  <!-- SCRIPTS -->
  <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>

</html>

contactapp/templates/contactapp/contact_form.html
{% extends "contactapp/base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <br>
      <h1>お問い合わせ</h1>
      <br>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">送信</button>
      </form>
      <br>
    </div>
  </div>
</div>
{% endblock %}

contactapp/templates/contactapp/index.html
{% extends 'contactapp/base.html' %}


{% block content %}
    <div class="row row-cols-1 row-cols-md-3">
  <div class="col mb-4">
    <h4>お問い合わせお待ちしております。</h4>
  </div>
</div>
{% endblock content %}
    